version: '3.5'

x-service-template: &service_template
    build:
      context: ./dora_bora
      dockerfile: ./Dockerfile
    volumes:
      - ./dora_bora:/workspace
    env_file: ./dora_bora/.env
    depends_on:
      - db
      - redis
      - static
    restart: on-failure
    user: "1000:1000"

services:
  db:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "0.0.0.0:5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    restart: on-failure
    user: "1000:1000"

  redis:
    image: redis:6.2-alpine
    restart: on-failure
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - redis:/data

  static:
    image: nginx
    ports:
        - 8000:80
    volumes:
        - ./static:/usr/share/nginx/html
    restart: on-failure

  management:
    <<: *service_template
    ports:
      - "5050:5050"
    command: ["management_server"]

  login:
    <<: *service_template
    ports:
      - "5052:5052"
    command: ["login_server"]

  game:
    <<: *service_template
    ports:
      - "5052:5052"
    command: ["game_server"]


volumes:
  redis:
    driver: local