version: '3.5'

services:
  db:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "0.0.0.0:5432:5432"
    command: ["postgres", "-c", "log_statement=all"]

  redis:
    image: redis:6.2-alpine
    restart: on-failure
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - redis:/data

  management:
    build:
      context: ./management
      dockerfile: ./Dockerfile
    volumes:
      - ./management:/workspace
    ports:
      - "5050:5050"
    env_file: ./management/.env
    depends_on:
      - db
      - redis
    restart: on-failure
    user: "1000:1000"

  login:
    build:
      context: ./login
      dockerfile: ./Dockerfile
    volumes:
      - ./login:/workspace
    ports:
      - "5051:5051"
    env_file: ./login/.env
    depends_on:
      - db
      - redis
    restart: on-failure
    user: "1000:1000"

  game:
    build:
      context: ./game
      dockerfile: ./Dockerfile
    volumes:
      - ./game:/workspace
    ports:
      - "5052:5052"
    env_file: ./game/.env
    depends_on:
      - db
      - redis
    restart: on-failure
    user: "1000:1000"

  static:
    image: nginx
    ports:
        - 8000:80
    volumes:
        - ./static:/usr/share/nginx/html

volumes:
  redis:
    driver: local