# Generated by Django 5.0.1 on 2024-02-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_account_is_game_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='switch_token',
            field=models.CharField(blank=True, default='', max_length=1023),
        ),
    ]
