# Generated by Django 5.0.1 on 2024-01-07 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[("offline", "Offline"), ("online", "Online"), ("maintenance", "Maintenance")],
                        max_length=255,
                    ),
                ),
                ("subscriber_only", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nickname", models.CharField(max_length=255, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("offline", "Offline"),
                            ("in_login", "In Login"),
                            ("in_game", "In Game"),
                            ("banned", "Banned"),
                        ],
                        default="offline",
                        max_length=255,
                    ),
                ),
                ("subscribed_until", models.DateTimeField()),
                ("security_question", models.CharField(max_length=511)),
                ("community", models.IntegerField(choices=[(0, "Zero")], default=0)),
                (
                    "dj_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="account", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
