# Generated by Django 5.0.1 on 2024-01-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="switch_token",
            field=models.CharField(default=True, max_length=1023, null=True),
        ),
    ]
