# Generated by Django 5.0.1 on 2024-01-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capabilities', models.IntegerField()),
                ('date', models.CharField(max_length=255)),
                ('dofus_id', models.IntegerField(unique=True)),
                ('fix_size', models.IntegerField()),
                ('forbidden', models.JSONField(default=list)),
                ('group_count', models.IntegerField()),
                ('height', models.IntegerField()),
                ('key', models.TextField(blank=True, null=True)),
                ('raw_map_data', models.TextField()),
                ('map_data', models.JSONField(blank=True, null=True)),
                ('max_size', models.IntegerField()),
                ('min_size', models.IntegerField()),
                ('monsters', models.JSONField(blank=True, default=list)),
                ('places', models.JSONField(blank=True, default=list)),
                ('position', models.JSONField(default=list)),
                ('sniffed', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
        ),
    ]
