# Generated by Django 5.0.1 on 2024-01-07 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_class', models.IntegerField(choices=[(1, 'Feca'), (2, 'Osamodas'), (3, 'Enutrof'), (4, 'Sram'), (5, 'Xelor'), (6, 'Ecaflip'), (7, 'Eniripsa'), (8, 'Iop'), (9, 'Cra'), (10, 'Sadida'), (11, 'Sacrieur'), (12, 'Pandawa')])),
                ('colors', models.JSONField(default=list)),
                ('energy', models.IntegerField(default=10000)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('kamas', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('spell_points', models.IntegerField(default=0)),
                ('stat_points', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='Login.account')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='Login.server')),
            ],
        ),
    ]
