# Generated by Django 5.0.1 on 2024-01-08 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0001_initial'),
        ('Map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='Map.map'),
        ),
    ]
