# Generated by Django 5.0.1 on 2024-02-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='initiative',
        ),
        migrations.AddField(
            model_name='character',
            name='action_points',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='character',
            name='action_points_dodge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='agility',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='air_resistance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='current_hit_points',
            field=models.IntegerField(default=55),
        ),
        migrations.AddField(
            model_name='character',
            name='earth_resistance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='fire_resistance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='inteligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='luck',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='max_hit_points',
            field=models.IntegerField(default=55),
        ),
        migrations.AddField(
            model_name='character',
            name='movement_points',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='character',
            name='movement_points_dodge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='neutral_resistance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='water_resistance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='wisdom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='map',
            name='key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
