# Generated by Django 5.0.1 on 2024-01-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_remove_map_dofus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='doors',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
