# Generated by Django 5.0.1 on 2024-01-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_map_doors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('gfx_id', models.IntegerField()),
                ('alignment', models.IntegerField(null=True)),
                ('colors', models.JSONField(default=list)),
                ('ranks', models.JSONField(default=dict)),
                ('kama_rewards', models.JSONField(default=list)),
                ('ai_id', models.IntegerField()),
                ('capturable', models.BooleanField(default=True)),
                ('aggression_range', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
